"""중간 시안 품질 루프용 입력 코퍼스 12건 (로컬 고정, LLM·DB 불필요).

각 케이스는 new_card()+_put() 규칙 조립만으로 카드를 만든다.
NIM·채팅·사진 파일을 쓰지 않는다. 사진 있는 케이스는 URL 문자열만 넣는다.
사용법: .venv/bin/python scripts/draft_lab.py --list
"""
from app.services import prd_engine as E
from app.services import prd_schema as S

CASES = [
    {"id": "cafe-talkative", "industry": "cafe", "photo": False,
     "slots": {"business_type": "카페", "shop_name": "마포 느린오후",
               "offerings": ["아메리카노", "카페라떼", "바스크치즈케이크"],
               "phone": "02-123-4567", "hours": "매일 10~21시",
               "location": "서울 마포구 연남로 12", "detail": "창가 자리가 넓은 조용한 카페예요."}},
    {"id": "cafe-owner-photo", "industry": "cafe", "photo": True,
     "slots": {"business_type": "카페", "shop_name": "마포 느린오후",
               "offerings": ["아메리카노", "카페라떼"],
               "phone": "02-123-4567", "hours": "매일 10~21시",
               "detail": "창가 자리가 넓은 조용한 카페예요."}},
    {"id": "restaurant-terse", "industry": "restaurant", "photo": False,
     "slots": {"business_type": "식당", "shop_name": "황남밥상",
               "offerings": ["김치찌개", "된장찌개"]}},
    {"id": "restaurant-changes", "industry": "restaurant", "photo": False,
     "slots": {"business_type": "식당", "shop_name": "황남밥상",
               "offerings": ["김치찌개", "제육볶음", "계란말이"],
               "hours": "평일 11~20시", "detail": "반찬을 직접 담그는 집밥 식당이에요."}},
    {"id": "salon-no-photo", "industry": "salon", "photo": False,
     "slots": {"business_type": "미용실", "shop_name": "단정손끝",
               "offerings": ["컷", "염색", "펌"], "hours": "10~19시, 월요일 휴무"}},
    {"id": "salon-photo", "industry": "salon", "photo": True,
     "slots": {"business_type": "미용실", "shop_name": "단정손끝",
               "offerings": ["컷", "염색"], "phone": "010-1111-2222"}},
    {"id": "academy-talkative", "industry": "academy", "photo": False,
     "slots": {"business_type": "영어 학원", "shop_name": "믿음영어",
               "offerings": ["초등 파닉스반", "중등 내신반", "고등 수능반"],
               "hours": "평일 14~22시", "location": "서울 노원구 상계로 77",
               "contact_method": "사이트에서 상담 신청",
               "detail": "반 정원이 8명인 동네 영어 학원이에요."}},
    {"id": "pension-family", "industry": "pension", "photo": False,
     "slots": {"business_type": "펜션", "shop_name": "숲속의 쉼",
               "offerings": ["101호(복층)", "102호(온돌)", "바베큐장"],
               "hours": "입실 15시·퇴실 11시", "location": "강원 평창군 봉평면",
               "detail": "아이와 함께 오기 좋은 조용한 펜션이에요."}},
    {"id": "cello-lesson", "industry": "individual", "photo": False,
     "slots": {"business_type": "첼로 레슨", "shop_name": "하늘첼로",
               "offerings": ["성인 취미반", "입시반"],
               "hours": "화·목 18~21시", "detail": "처음 만나는 첼로가 평생의 취미가 되도록 가르쳐요."}},
    {"id": "group-workshop", "industry": "group", "photo": True,
     "slots": {"business_type": "도예 모임", "shop_name": "흙손모임",
               "offerings": ["주말 원데이클래스", "4주 정규반"],
               "detail": "손으로 만드는 시간을 함께하는 모임이에요."}},
    {"id": "webservice-tool", "industry": "webservice", "photo": False,
     "slots": {"business_type": "예약 관리 웹서비스", "shop_name": "예약잇기",
               "offerings": ["문자 알림", "노쇼 관리"],
               "detail": "작은 가게의 예약을 대신 받아주는 서비스예요."}},
    {"id": "other-minimal", "industry": "other", "photo": False,
     "slots": {"business_type": "동네 가게"}},
]


def build_card(case: dict) -> dict:
    """케이스 → 카드. 사실 슬롯은 FILLED, 사진은 URL 문자열만."""
    card = E.new_card(case["industry"])
    for key, value in case["slots"].items():
        E._put(card, key, value, S.FILLED, 1)
    # 가격 짝 (실제 대화 경로와 같게: price 칸 값을 넣은 뒤 짝을 기록한다).
    price = case["slots"].get("price")
    if price:
        E._record_price_pairs(card, [{"slot": "price", "value": price}], price)
    card["turn"] = 1
    if case.get("photo"):
        rid = "lab-" + case["id"]
        card["photos"] = [
            {"id": "p1", "url": f"/uploads/{rid}/p1.jpg", "caption": "대표 사진"},
            {"id": "p2", "url": f"/uploads/{rid}/p2.jpg", "caption": "내부 사진"},
        ]
    return card



def get(case_id: str) -> dict:
    for c in CASES:
        if c["id"] == case_id:
            return c
    raise KeyError(case_id)


# 적합성 채점(scripts/draft_fit.py)용 케이스 (DESIGN_FIT_PLAN §5).
# 가격·디자이너·분류·주소가 들어 있고, expect에 시안에 반드시 보여야 할 것을 적는다.
# mode·categories는 1단계(상황 탐색)가 카드에 넣을 값이다. 그 전에는 채점기만 읽는다.
FIT_CASES = [
    {"id": "fit-cafe-dinein", "industry": "cafe", "photo": False, "mode": "dinein",
     "slots": {"business_type": "카페", "shop_name": "연남 느린오후",
               "offerings": ["아메리카노", "카페라떼", "딸기라떼", "유자에이드", "바스크치즈케이크", "휘낭시에"],
               "price": "아메리카노 4,500원, 카페라떼 5,000원, 바스크치즈케이크 6,500원",
               "phone": "02-123-4567", "hours": "매일 10~21시", "location": "서울 마포구 연남로 12",
               "detail": "창가 자리가 넓은 조용한 카페예요."},
     "expect": {"action": ("길찾기", "오시는 길"), "action_sections": ("around",),
                "categories": ("커피", "음료", "디저트"),
                "pairs": (("아메리카노", "4,500원"), ("카페라떼", "5,000원"), ("바스크치즈케이크", "6,500원")),
                "staff": (), "staff_mode": ""}},
    {"id": "fit-cafe-pickup", "industry": "cafe", "photo": False, "mode": "pickup",
     "slots": {"business_type": "카페", "shop_name": "연남 느린오후",
               "offerings": ["아메리카노", "카페라떼", "바스크치즈케이크"],
               "price": "아메리카노 4,500원, 카페라떼 5,000원, 바스크치즈케이크 6,500원",
               "phone": "02-123-4567", "hours": "매일 10~21시", "location": "서울 마포구 연남로 12",
               "contact_method": "픽업 주문"},
     "expect": {"action": ("주문",), "action_sections": ("offerings",),
                "categories": ("커피", "디저트"),
                "pairs": (("아메리카노", "4,500원"), ("바스크치즈케이크", "6,500원")),
                "staff": (), "staff_mode": ""}},
    {"id": "fit-salon-solo", "industry": "salon", "photo": False, "mode": "solo",
     "slots": {"business_type": "미용실", "shop_name": "단정손끝",
               "offerings": ["컷", "펌", "클리닉"], "price": "컷 2만원, 펌 8만원",
               "staff": ["원장 김단정(컷·펌)"], "hours": "10~19시, 월요일 휴무",
               "location": "서울 마포구 성미산로 21"},
     "expect": {"action": ("예약",), "action_sections": ("booking",), "categories": (),
                "pairs": (("컷", "2만원"), ("펌", "8만원")),
                "staff": ("김단정",), "staff_mode": "solo"}},
    {"id": "fit-salon-team", "industry": "salon", "photo": False, "mode": "team",
     "slots": {"business_type": "미용실", "shop_name": "살롱 드 연남",
               "offerings": ["컷", "염색", "펌"], "price": "컷 2만5천원, 염색 9만원, 펌 12만원",
               "staff": ["원장 김미용(컷)", "실장 박하나(염색)", "디자이너 이서준(펌)"],
               "phone": "02-333-4444", "hours": "10~20시", "location": "서울 마포구 동교로 30"},
     "expect": {"action": ("예약",), "action_sections": ("booking", "staff"), "categories": (),
                "pairs": (("컷", "2만5천원"), ("염색", "9만원"), ("펌", "12만원")),
                "staff": ("김미용", "박하나", "이서준"), "staff_mode": "team"}},
    {"id": "fit-pension", "industry": "pension", "photo": False, "mode": "",
     "slots": {"business_type": "펜션", "shop_name": "숲속의 쉼",
               "offerings": ["101호 복층", "102호 온돌"], "price": "101호 복층 18만원, 102호 온돌 12만원",
               "hours": "입실 15시·퇴실 11시", "location": "강원 평창군 봉평면 무이로 45",
               "phone": "033-000-1111"},
     "expect": {"action": ("예약",), "action_sections": ("booking", "offerings"), "categories": (),
                "pairs": (("101호 복층", "18만원"), ("102호 온돌", "12만원")),
                "staff": (), "staff_mode": ""}},
    {"id": "fit-academy", "industry": "academy", "photo": False, "mode": "",
     "slots": {"business_type": "영어 학원", "shop_name": "믿음영어",
               "offerings": ["초등 파닉스반", "중등 내신반"],
               "price": "초등 파닉스반 월 18만원, 중등 내신반 월 24만원",
               "staff": ["김믿음 원장(초등)"], "target": "초등·중학생",
               "location": "서울 노원구 상계로 77", "phone": "02-777-8888"},
     "expect": {"action": ("상담",), "action_sections": ("booking", "contact"), "categories": (),
                "pairs": (("초등 파닉스반", "월 18만원"), ("중등 내신반", "월 24만원")),
                "staff": ("김믿음",), "staff_mode": "solo"}},
    {"id": "fit-pension-full", "industry": "pension", "photo": False, "mode": "",
     "slots": {"business_type": "펜션", "shop_name": "숲속의 쉼",
               "offerings": ["101호 복층 4인", "102호 온돌 2인", "바베큐장"],
               "price": "101호 복층 18만원, 102호 온돌 12만원",
               "hours": "입실 15시·퇴실 11시", "location": "강원 평창군 봉평면 무이로 45",
               "phone": "033-000-1111"},
     "expect": {"action": ("예약",), "action_sections": ("booking", "rooms"), "categories": (),
                "pairs": (("101호 복층", "18만원"), ("102호 온돌", "12만원")),
                "staff": (), "staff_mode": ""}},
    {"id": "fit-pension-min", "industry": "pension", "photo": False, "mode": "",
     "slots": {"business_type": "펜션", "shop_name": "숲속의 쉼",
               "offerings": ["201호", "바베큐장"],
               "location": "강원 평창군 봉평면"},
     "expect": {"action": ("예약",), "action_sections": ("booking", "rooms"), "categories": (),
                "pairs": (), "staff": (), "staff_mode": ""}},
    {"id": "fit-academy-full", "industry": "academy", "photo": False, "mode": "",
     "slots": {"business_type": "영어 학원", "shop_name": "믿음영어",
               "offerings": ["초등 파닉스반 월수 16시 8명", "중등 내신반 화목 18시 정원 10명", "고등 수능반 금 19시"],
               "price": "초등 파닉스반 월 18만원, 중등 내신반 월 24만원, 고등 수능반 월 25만원",
               "staff": ["김믿음 원장(초등)", "이열심 강사(중등)"],
               "phone": "02-777-8888", "hours": "평일 14~22시",
               "location": "서울 노원구 상계로 77"},
     "expect": {"action": ("상담",), "action_sections": ("booking", "classes"), "categories": (),
                "pairs": (("초등 파닉스반", "월 18만원"), ("중등 내신반", "월 24만원"), ("고등 수능반", "월 25만원")),
                "staff": ("김믿음", "이열심"), "staff_mode": "team"}},
    {"id": "fit-academy-min", "industry": "academy", "photo": False, "mode": "",
     "slots": {"business_type": "영어 학원", "shop_name": "믿음영어",
               "offerings": ["중등 내신반 화목 18시"],
               "staff": ["김믿음 원장"],
               "location": "서울 노원구 상계로 77"},
     "expect": {"action": ("상담",), "action_sections": ("booking", "classes"), "categories": (),
                "pairs": (), "staff": ("김믿음",), "staff_mode": "solo"}},
    {"id": "fit-restaurant", "industry": "restaurant", "photo": False, "mode": "dinein",
     "slots": {"business_type": "식당", "shop_name": "황남밥상",
               "offerings": ["김치찌개", "제육볶음", "계란말이"],
               "price": "김치찌개 9천원, 제육볶음 1만원, 계란말이 8천원",
               "phone": "02-555-6666", "hours": "평일 11~20시",
               "location": "서울 마포구 성미산로 33",
               "detail": "반찬을 직접 담그는 집밥 식당이에요."},
     "expect": {"action": ("길찾기", "오시는 길"), "action_sections": ("around",),
                "categories": (),
                "pairs": (("김치찌개", "9천원"), ("제육볶음", "1만원"), ("계란말이", "8천원")),
                "staff": (), "staff_mode": ""}},
    {"id": "fit-nail", "industry": "salon", "photo": False, "mode": "team",
     "slots": {"business_type": "네일", "shop_name": "반짝손톱",
               "offerings": ["젤네일", "아트네일", "케어"],
               "price": "젤네일 5만원, 아트네일 6만원, 케어 2만원",
               "staff": ["원장 김네일(젤네일)", "실장 박아트(아트네일)"],
               "phone": "010-7777-8888", "hours": "10~20시",
               "location": "서울 마포구 동교로 44"},
     "expect": {"action": ("예약",), "action_sections": ("booking", "staff"), "categories": (),
                "pairs": (("젤네일", "5만원"), ("아트네일", "6만원"), ("케어", "2만원")),
                "staff": ("김네일", "박아트"), "staff_mode": "team"}},
    {"id": "fit-workshop-full", "industry": "workshop", "photo": False, "mode": "",
     "slots": {"business_type": "도예 공방", "shop_name": "흙내음 도예",
               "offerings": ["원데이 도예 토 14시 6명", "4주 정규반 수 19시 8명", "어린이 흙놀이 일 11시 10명"],
               "price": "원데이 도예 3만5천원, 4주 정규반 18만원, 어린이 흙놀이 2만원",
               "staff": ["김흙내음 대표(도예)", "박물레 강사(물레)"],
               "phone": "02-111-2222", "hours": "화~일 10~18시, 월요일 휴무",
               "location": "서울 마포구 성미산로 15",
               "detail": "손으로 빚는 시간을 함께하는 동네 도예 공방이에요."},
     "expect": {"action": ("신청",), "action_sections": ("booking", "classes"), "categories": (),
                "pairs": (("원데이 도예", "3만5천원"), ("4주 정규반", "18만원"), ("어린이 흙놀이", "2만원")),
                "staff": ("김흙내음", "박물레"), "staff_mode": "team"}},
    {"id": "fit-workshop-min", "industry": "workshop", "photo": False, "mode": "",
     "slots": {"business_type": "가죽 공방", "shop_name": "손바느질 가죽",
               "offerings": ["원데이 카드지갑 토 14시 4명"]},
     "expect": {"action": ("신청",), "action_sections": ("booking", "classes"), "categories": (),
                "pairs": (), "staff": (), "staff_mode": ""}},
    {"id": "fit-workshop-unusual", "industry": "workshop", "photo": False, "mode": "",
     "slots": {"business_type": "장난감 수리 공방", "shop_name": "토이닥터 공방",
               "offerings": ["원데이 장난감 수리 토 14시 6명", "4주 수리반 목 19시 8명"],
               "price": "원데이 장난감 수리 2만원, 4주 수리반 12만원",
               "staff": ["최고침 대표(수리)"],
               "phone": "02-999-0000", "hours": "수~일 11~19시",
               "location": "서울 동작구 상도로 20",
               "detail": "고장난 장난감을 고쳐 쓰는 법을 나누는 수리 공방이에요."},
     "expect": {"action": ("신청",), "action_sections": ("booking", "classes"), "categories": (),
                "pairs": (("원데이 장난감 수리", "2만원"), ("4주 수리반", "12만원")),
                "staff": ("최고침",), "staff_mode": "solo"}},
    {"id": "fit-individual-full", "industry": "individual", "photo": False, "mode": "",
     "slots": {"business_type": "출장 사진", "shop_name": "빛담 스냅",
               "offerings": ["프로필 촬영 1시간", "가족 사진 2시간"],
               "price": "프로필 촬영 1시간 15만원, 가족 사진 2시간 25만원",
               "phone": "010-2222-3333", "hours": "예약제, 주말 가능",
               "location": "서울 마포구 성미산로 21",
               "detail": "자연광으로 편안한 표정을 담는 출장 사진가예요."},
     "expect": {"action": ("문의", "견적"), "action_sections": ("contact",), "categories": (),
                "pairs": (("프로필 촬영 1시간", "15만원"), ("가족 사진 2시간", "25만원")),
                "staff": (), "staff_mode": ""}},
    {"id": "fit-individual-min", "industry": "individual", "photo": False, "mode": "",
     "slots": {"business_type": "인테리어 디자인", "shop_name": "한칸 디자인",
               "offerings": ["원룸 인테리어 상담"]},
     "expect": {"action": ("문의", "견적"), "action_sections": ("contact",), "categories": (),
                "pairs": (), "staff": (), "staff_mode": ""}},
    {"id": "fit-individual-unusual", "industry": "individual", "photo": False, "mode": "",
     "slots": {"business_type": "반려동물 장례 상담", "shop_name": "마지막산책 상담소",
               "offerings": ["일대일 장례 상담", "추모 예식 동행"],
               "price": "일대일 장례 상담 5만원, 추모 예식 동행 10만원",
               "phone": "010-4444-5555", "hours": "매일 10~20시",
               "detail": "반려동물과의 이별을 돕는 일대일 상담소예요."},
     "expect": {"action": ("문의", "견적"), "action_sections": ("contact",), "categories": (),
                "pairs": (("일대일 장례 상담", "5만원"), ("추모 예식 동행", "10만원")),
                "staff": (), "staff_mode": ""}},
    {"id": "fit-group-full", "industry": "group", "photo": False, "mode": "",
     "slots": {"business_type": "독서 모임", "shop_name": "월빛독서모임",
               "offerings": ["월요 고전 읽기", "금요 신간 나누기"],
               "price": "월요 고전 읽기 월 2만원, 금요 신간 나누기 월 2만원",
               "staff": ["이책사랑 대표(진행)", "김밑줄 팀장(기록)"],
               "phone": "010-6666-7777", "hours": "월·금 19~21시",
               "location": "서울 마포구 동교로 50",
               "detail": "매주 모여 책을 읽고 나누는 동네 독서 모임이에요."},
     "expect": {"action": ("가입", "문의", "참여"), "action_sections": ("contact", "booking"), "categories": (),
                "pairs": (("월요 고전 읽기", "월 2만원"), ("금요 신간 나누기", "월 2만원")),
                "staff": ("이책사랑", "김밑줄"), "staff_mode": "team"}},
    {"id": "fit-group-min", "industry": "group", "photo": False, "mode": "",
     "slots": {"business_type": "등산 모임", "shop_name": "주말등산모임",
               "offerings": ["토요 북한산 산행"]},
     "expect": {"action": ("가입", "문의", "참여"), "action_sections": ("contact", "booking"), "categories": (),
                "pairs": (), "staff": (), "staff_mode": ""}},
    {"id": "fit-group-unusual", "industry": "group", "photo": False, "mode": "",
     "slots": {"business_type": "아빠 육아 모임", "shop_name": "슈퍼아빠모임",
               "offerings": ["토요 놀이터 모임", "육아 고민 나누기"],
               "price": "토요 놀이터 모임 5천원, 육아 고민 나누기 5천원",
               "phone": "010-1212-3434", "hours": "토 10~12시",
               "location": "서울 은평구 증산로 40",
               "detail": "아빠들이 모여 육아를 나누는 주말 모임이에요."},
     "expect": {"action": ("가입", "문의", "참여"), "action_sections": ("contact", "booking"), "categories": (),
                "pairs": (("토요 놀이터 모임", "5천원"), ("육아 고민 나누기", "5천원")),
                "staff": (), "staff_mode": ""}},
    {"id": "fit-webservice-full", "industry": "webservice", "photo": False, "mode": "",
     "slots": {"business_type": "예약 관리 웹서비스", "shop_name": "예약잇기",
               "offerings": ["문자 알림", "노쇼 관리", "매출 통계"],
               "price": "문자 알림 월 1만원, 노쇼 관리 월 2만원, 매출 통계 월 3만원",
               "phone": "070-8888-9999", "hours": "평일 9~18시 고객센터",
               "detail": "작은 가게의 예약을 대신 받아주는 웹서비스예요."},
     "expect": {"action": ("시작", "문의", "신청"), "action_sections": ("contact", "offerings"), "categories": (),
                "pairs": (("문자 알림", "월 1만원"), ("노쇼 관리", "월 2만원"), ("매출 통계", "월 3만원")),
                "staff": (), "staff_mode": ""}},
    {"id": "fit-webservice-min", "industry": "webservice", "photo": False, "mode": "",
     "slots": {"business_type": "일정 공유 웹서비스", "shop_name": "같이보기",
               "offerings": ["모임 일정 공유"]},
     "expect": {"action": ("시작", "문의", "신청"), "action_sections": ("contact", "offerings"), "categories": (),
                "pairs": (), "staff": (), "staff_mode": ""}},
    {"id": "fit-webservice-unusual", "industry": "webservice", "photo": False, "mode": "",
     "slots": {"business_type": "어르신 병원 동행 중개 웹서비스", "shop_name": "동행잇기",
               "offerings": ["병원 동행 매칭", "진료 후 알림"],
               "price": "병원 동행 매칭 2만원, 진료 후 알림 5천원",
               "detail": "어르신 병원길에 동행자를 이어주는 웹서비스예요."},
     "expect": {"action": ("시작", "문의", "신청"), "action_sections": ("contact", "offerings"), "categories": (),
                "pairs": (("병원 동행 매칭", "2만원"), ("진료 후 알림", "5천원")),
                "staff": (), "staff_mode": ""}},
]
